- hosts: jumpbox
  gather_facts: False
#  roles:
#   - osp-network
#   - osp-keypair
#   - osp-securitygroup
  tasks:
  
#  - name: Create app1 instance
#    include_role:
#       name: osp-instances
#       vars_from: app1.yml
#  - name: Create app2 instance
#    include_role:
#       name: osp-instances
#       vars_from: app2.yml
  - name: Create frontend instance
    include_role:
     name: osp-instances
     vars_from: frontend.yml
  - name: Create app1 instance
    include_role:
     name: osp-instances
     vars_from: app1.yml
  - name: Create app2 instance
    include_role:
     name: osp-instances
     vars_from: app2.yml
  - name: Create db instance
    include_role:
     name: osp-instances
     vars_from: db.yml
  - name: Gather facts
    include_role: 
     name: osp-facts
    tags:
     - test_inventory

- hosts: appdbs
  gather_facts: True
  name: Configure DB Server
  roles:
   - appdbs
  
- hosts: apps
  gather_facts: True 
  name: Configuring App Server
  roles:
   - apps

- hosts: frontends
  gather_facts: True
  name: Configuring FrontEnd Server
  roles:
   - frontends
  tags: frontend
