---
- name: Generate key files
  user:
   name: root
   generate_ssh_key: yes
   ssh_key_file: "/root/.ssh/test_id_rsa"
- os_keypair:
   cloud: ospcloud
   state: present
   name: ansible_ssh
   public_key_file: "/root/.ssh/test_id_rsa.pub"



